<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN CONTENT -->
    <div class=" page-content-wrapper">
        <div class="page-content landing-content">
        <br/>
            <div class="col-md-12 "> 
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-folder"></i>Contact Us
                        </div>
                    </div>
                    <div class="portlet-body">                        
                        This page is under construction and will appear soon!
                        <div class="clearfix margin-bottom-20">
                        </div>                       

                    </div>
                </div>
            </div>
            <!-- BEGIN  PATNERS -->
            <div class="row" style="height:400px;"></div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="tab-content stake-holder">stakeholders</div>
                    <div style="float:right; padding-top: 35px; padding-right: 20px;"><img src="<?php echo $this->baseUrl(); ?>/images/usa-delivered-logo.png" alt=""/></div>
                    <ul class="nav nav-tabs stake-holder-list">
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/govt-of-pak-logo.png" alt=""/></li>
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/unicef-logo.png" alt=""/></li>
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/us-aid-logo.png" alt=""/></li>
                        <li> <img src="<?php echo $this->baseUrl(); ?>/common/assets/frontend/layout/img/vaccine-partners/who-logo.png" alt=""/></li>
                    </ul>                    
                </div>
            </div>
            <!-- END PATNERS -->
        </div></div>