<style>
h2 {
    font-family: "PT Sans Narrow",Helvetica,Arial,sans-serif;
    font-size: 22px;
    font-weight: normal;
    margin: 13px 0;
}

p {
    font-size: 13.5px;
    line-height: 150%;
    padding-bottom: 5px;
    text-align: left;
    margin: 0 0 10px;
}

a {
    font-size: 14.5px !important;
    color: #ffffff;
}

    
</style>

<!-- Tabs -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="innerLR">
            <div class="widget widget-tabs widget-tabs-double"  style=" border-bottom: 1px solid #77e588; border-right: 1px solid #77e588; border-top: 1px solid #77e588; margin-bottom: -2px;  ">

                <!-- Tabs Heading -->
                <div class="widget-head">
                    <ul>
                        <li class="active"><a class="glyphicons table"  href="#vaccines"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Vaccines</span></a></li>
                        <li><a   class="glyphicons table"  href="#courses"  data-toggle="tab"><i></i><span style="padding-top: 7px;font-weight:bold;font-size: 15px;">Courses</span></a></li>

                      
                    </ul>
                </div>
                <!-- // Tabs Heading END -->

                <div class="widget-body">
                    <div class="tab-content">

                        <!-- Tab content -->
                        <div id="vaccines" class="tab-pane active widget-body-regular">
                            <h2>Training of Trainer&#39;s Manual   <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/vlmis_tot_manual_draft.pdf">Download</a></h2>
                            <p>The manual is meant to train master trainers, who in turn will
                                conduct roll out trainings. It has two sections, section one
                                introduces the trainees to the Logistics concepts and Pakistan
                                Vaccine Logistics Management Information System (vLMIS) Software
                                and its related Tasks and Activities, whereas section two comprises
                                of sessions on training and communication skills.</p>
                            <p>Kindly note that this is a DRAFT version of document and feedback
                                received from participants and other stakeholders will be
                                incorporated after the trainings are completed. Also, being a
                                living document improvements and additions / deletions will be made
                                in due course of time.</p>

                            <h2>Participant&#39;s Guide  <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/vlmis_participants_guide_draft.pdf">Download</a></h2>
                            <p>The guide is meant for TOT participants use and contains
                                hand-outs, exercises and presentations relevant to training of
                                trainers manual.</p>
                            <p>Kindly note that this is a DRAFT version of document and feedback
                                received from participants and other stakeholders will be
                                incorporated after the trainings are completed. Also, being a
                                living document improvements and additions / deletions will be made
                                in due course of time.</p>
                            
                            <h2>Facilitators/Trainer&#39;s Manual  <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/vlmis_facilitator_manual_draft.pdf">Download</a></h2>
                            <p>This trainer manual is meant to be used by master trainers to
                                conduct roll out trainings on Pakistan Vaccine Logistics Management
                                Information System (vLMIS). It has sessions on logistics system and
                                its basic concepts and software related tasks and activities.
                                Trainers can use it as reference material during different types of
                                roll out trainings and orientation sessions at different levels.</p>
                            <p>Kindly note that this is a DRAFT version of document and feedback
                                received from participants and other stakeholders will be
                                incorporated after the trainings are completed. Also, being a
                                living document improvements and additions / deletions will be made
                                in due course of time.</p>
                            

                            <h2>vLMIS User Guide  <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/vlmis_user_manual_(roles_based)_draft.pdf">Download</a></h2>
                            <p>The Vaccines Logistics Management Information System User Manual
                                (Guide) provides step-by- step instructions that help you get
                                started with Vaccine Logistics Management Information System
                                (vLMIS) functions and features and provides guidelines on managing
                                relevant Vaccines Logistics data using the Vaccine Logistics
                                Management Information System accounts. This guide is organized
                                according to the logical flow of Vaccine Logistics Management
                                Information System features and describes tasks in the same order
                                you can use while working with the product.</p>
                            <p>Kindly note that this is a DRAFT version of document and feedback
                                received from participants and other stakeholders will be
                                incorporated after the trainings are completed. Also, being a
                                living document improvements and additions / deletions will be made
                                in due course of time.</p>
                            
                            <h2>Training Calendar / Plan  <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/provincial_training_plans.pdf">Download</a></h2>
                            <p>The training calendar outlines the province / region specific
                                schedule of different types of vLMIS Roll-Out trainings including
                                trainings on warehouse management system and consumption reporting
                                for data entry operators of 54 priority / high risk districts.
                                Further, the schedule of orientation sessions on vLMIS for EPI
                                policy makers and managers, and Cluster Lead In-charges can also be
                                accessed for different provinces and districts.</p>
                            

                            <h2>Database of Master Trainers and Health/EPI Officials  <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/training_database.pdf">Download</a></h2>
                            <p>The vLMIS Training Database lists the information including name,
                                designation, department, province/district of residence /
                                employment, type of training attended and dates of training
                                pertaining to Master Trainers and other health and EPI officials
                                trained or oriented on vLMIS, till February 25, 2014. Since roll
                                out training are in progress the database will be updated on weekly
                                basis.</p>
                            

                        </div>
                        <!-- // Tab content END -->

                        <!-- Tab content -->
                        <div id="courses" class="tab-pane widget-body-regular">
                        <p>For the first time Health Services Academy (HSA) Islamabad offers
                                following courses, in conjunction with the USAID|DELIVER Project;


                            <ul>
                                <li>Three Credit Course for Supply Chain Management of Public
                                    Health Commodities</li>
                                <li>Certificate Course on Supply Chain Management of Health
                                    Commodities</li>
                            </ul>

                            <p>The courses will help to increase the participants&#39; understanding
                                of the fundamentals of logistics management and the relationship
                                between supply chain logistics and commodity security. It also will
                                strengthen the participants&#39; ability to implement improvements
                                to basic elements of their logistics systems.
                            </p>

                            <h2>Lecturer&#39;s Guide: Three Credit Course for Supply Chain
                                Management of Public Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/three_credit_lecturer_guide.pdf">Download</a></h2>
                            <p>The Lecture Guide for the Three Credit Course on Supply Chain
                                Management of Public Health Commodities is meant for lecturers who
                                are supposed to conduct the course. This curriculum is written
                                following Adult Learning Theory principles which emphasize more
                                interactive and participatory approaches than traditional teaching
                                techniques. Small group exercises are placed into the curriculum
                                and Lecturers are encouraged to run these activities as written
                                where ever possible. The curriculum not only provides basic
                                principles for running a logistic system but includes elements that
                                are Pakistan specific. For this course each major unit of learning
                                is referred to as a Session and each section within is referred to
                                as an Activity. This course has 17 different Sessions. Lecturers
                                are highly encouraged to read the Lecturer Preparation section at
                                the beginning of each session well before leading each session.
                                Note that Synthesis Questions are presented at the end of each
                                Session. These can be used to ensure students are grasping the key
                                concepts of each session. Unlike the Certificate course this course
                                is competency-based.</p>
                            
                            <h2>Student Guide: Three Credit Course on Supply Chain Management of
                                Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/three_credit_student_guide.pdf">Download</a></h2>
                            <p>The Guide is meant for use of three credit course students.</p>
                            
                            <h2>Lecturer&#39;s Guide: Certificate Course on Supply Chain
                                Management of Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/certificate_course_lect_guide.pdf">Download</a></h2>

                            <p>The Lecture Guide for the Certificate Course on Supply Chain
                                Management of Public Health Commodities is meant for lecturers who
                                are supposed to conduct the course. This will become a three credit
                                course and likely expand to a larger offering in time. This
                                curriculum is written following Adult Learning Theory principles
                                which emphasize more interactive and participatory approaches than
                                traditional teaching techniques. Small group exercises are placed
                                into the curriculum and Lecturers are encouraged to run these
                                activities as written. The curriculum not only provides basic
                                principles for running a logistic system but includes elements that
                                are Pakistan specific. For this course each major unit of learning
                                is referred to as a Session and each part of a Session is referred
                                to as an Activity. This course has 16 different Sessions. Lecturers
                                are highly encouraged to read the &#39;Lecturer Preparation&#39;
                                section at the beginning of each session well before leading each
                                session.</p>
                            
                            <h2>Student Handbook: Certificate Course on Supply Chain Management
                                of Health Commodities  <a class="btn btn-primary input-sm" target="_blank"
                               href="http://lmis.gov.pk/training_manuals/certificate_course_student_guide.pdf">Download</a></h2>

                            <p>The handbook is meant for use of certificate course students.</p>
                            


    
                        
                        
                        
                        
                        </div>
                        <!-- // Tab content END -->





                    </div>
                </div>
            </div>
            <!-- // Tabs END -->
        </div>
    </div>
</div>