<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content"> 
        <?php if (isset($this->success)) { ?>
            <div class="alert alert-success alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button>
                <strong>Success!</strong> <?php echo $this->success; ?>
            </div>
        <?php } ?>
        <?php if (isset($this->error)) { ?>
            <div class="alert alert-danger alert-dismissable">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button>
                <strong>Error!</strong> <?php echo $this->error; ?>
            </div>
        <?php } ?>
        <h3 class="page-title">
            <?php echo $this->translate("Log book of children vaccinated from outside UCs"); ?>
        </h3>
        <form method="POST" name="stock_issue" id="stock_issue" action="" >
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <?php echo $this->translate("Fill Form"); ?>
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse"></a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="row">
                                <div class="col-md-12">  

                                    <!-- Row -->
                                    <div class="row">


                                        <div class="col-md-3">
                                            <label class="control-label" for="vaccination_date">
                                                <?php echo $this->translate("Vaccinatin Date"); ?>
                                            </label>
                                            <div class="controls">
                                                <input id="vaccination_date" class="form-control" type="text" readonly="readonly" value="" name="vaccination_date">
                                            </div>
                                        </div>   


                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>   

            <div class="row">
                <div class="col-md-12">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <?php echo $this->translate("Fill Form"); ?>
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse">
                                </a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped table-bordered table-condensed">
                                        <!-- Table heading -->
                                        <thead>
                                            <tr>
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("S.No"); ?>
                                                </th>
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("Name"); ?>
                                                </th>
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("Father Name"); ?>
                                                </th>
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("Age"); ?>
                                                </th>
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("Contact"); ?>
                                                </th>
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("Address"); ?>
                                                </th>
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("District"); ?>
                                                </th>
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("Union Council"); ?>
                                                </th>

                                                <th class="center" colspan="5" style="font-size:12px" >
                                                    <?php echo $this->translate("Dose No."); ?>
                                                </th>   
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("Refer from"); ?>
                                                </th> 
                                                <th rowspan="2" style="font-size:12px">
                                                    <?php echo $this->translate("Remarks"); ?>
                                                </th>  


                                            </tr>

                                            <tr>
                                                <?php foreach ($this->items as $row) { ?>
                                                    <th style="font-size:12px"><?php
                                                        if ($row['item_name'] == 'Pentavalent-1') {
                                                            echo 'Penta-1';
                                                        } else if ($row['item_name'] == 'Pneumococcal-2 (PCV10)') {
                                                            echo '(PCV10)';
                                                        } else if ($row['item_name'] == 'Measles-10') {
                                                            echo 'Measles';
                                                        } else {

                                                            echo $row['item_name'];
                                                        }
                                                        ?></th>

                                                <?php } ?>
                                            </tr>
                                        </thead>
                                        <!-- // Table heading END -->

                                        <!-- Table body -->
                                        <tbody>
                                            <!-- Table row -->
                                            <?php
                                            $j = 1;
                                            for ($i = $this->start; $i < $this->end; $i++) {
                                                $rows = "rows" . $i;
                                                $j = $i + 1;
                                                ?>
                                                <tr class="dynamic-rows">
                                                    <td class="serial">
                                                        <?php echo $j; ?>
                                                        <input type="hidden" name="serial_number[]" value="<?php echo $j; ?>">
                                                    </td>
                                                    <td>
                                                        <input type="text" class="form-control" value="" id="name" name="name[]">
                                                    </td>
                                                    <td>
                                                        <input id="father_name" class="form-control" type="text" value="" name="father_name[]">
                                                    </td>
                                                    <td width="4%">
                                                        <input id="age" class="form-control" type="text" value="" name="age[]">
                                                    </td>
                                                    <td>
                                                        <input id="contact" class="form-control" type="text" value="" name="contact[]">
                                                    </td>
                                                    <td>
                                                        <input id="address" class="form-control" type="text" value="" name="address[]">
                                                    </td>

                                                    <td>
                                                        <select id="<?php echo $j; ?>-district" class="form-control" name="district[]" style=" padding: 0px; width:70px ">
                                                            <option value=""><?php echo $this->translate("Select"); ?></option>
                                                            <?php
                                                            foreach ($this->locations as $row) {
                                                                ?>
                                                                <option value="<?php echo $row['pkId']; ?>" >
                                                                    <?php echo $row['locationName']; ?>
                                                                </option>
                                                                <?php
                                                            }
                                                            ?>

                                                        </select>
                                                    </td>
                                                    <td>
                                                        <select id="<?php echo $j; ?>-uc" class="form-control" name="uc[]" style=" padding: 0px; width:70px"> 
                                                            <option value=""><?php echo $this->translate("Select"); ?></option>
                                                        </select>
                                                    </td>


                                                    <?php foreach ($this->items as $row) { ?>
                                                        <td width="5%">
                                                            <input type="hidden" name="<?php echo $j; ?>_item_id[]" value="<?php echo $row['pk_id'] ?>">
                                                            <input id="<?php echo $row['pk_id'] ?>-item" class="form-control" type="text" value="" name="<?php echo $j; ?>_dose_no[]" size="25px">
                                                        </td>
                                                    <?php } ?>
                                                    <td>
                                                        <input type="text" class="form-control" value="" id="reffers_to" name="reffers_to[]">
                                                    </td>
                                                    <td>
                                                        <input type="text" class="form-control" value="" id="remarks" name="remarks[]">
                                                    </td>

                                                </tr>
                                                <?php
                                            }
                                            ?>
                                            <!-- // Table row END -->
                                        </tbody>
                                        <!-- // Table body END -->                                      

                                    </table>
                                </div>
                            </div>
                            <br/>
                            <div class="row">
                                <div class="col-md-10">   
                                    <button id="add_stock" type="submit" class="btn btn-primary">
                                        <?php echo $this->translate("Save"); ?>
                                    </button>                                    
                                    <input type="hidden" value="<?php echo $this->end; ?>" name="counter" id="counter" />
                                </div>                                
                                <!--                                <div class="col-md-1">
                                                                    <button id="add_more" type="button" class="btn blue">
                                <?php echo $this->translate("Add rows"); ?>
                                                                    </button>
                                                                </div>
                                                                <div class="col-md-1 right">
                                                                    <input type="text" value="5" id="default_counter" class="form-control" />
                                                                </div>-->

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<a id="notific8_show" href="javascript:;" class="hide"></a>
<div id="notific8_heading" class="hide">Your Data</div>
<div id="notific8_life" class="hide">5000</div>
<div id="notific8_text" class="hide">has been saved as draft.</div>

<div style="display: none;">
    <div id="clevel"><?php echo $this->params['office']; ?></div>
    <div id="cprov"><?php echo $this->params['province']; ?></div>
    <div id="cdist"><?php echo $this->params['district']; ?></div>
    <div id="cwh"><?php echo $this->params['warehouse']; ?></div>
</div>