<!-- Content -->
<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title"><?php echo $this->translate("Stock in Bin"); ?> - <?php echo $this->title; ?></h3>
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <a style="color:#fff;" href="<?php echo $this->baseUrl(); ?>/stock/location-status-vaccines?id=<?php echo $this->id; ?>"><?php echo $this->translate("Back to Location"); ?></a>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <?php
                                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                                ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <?php if (isset($_GET['success']) && $_GET['success'] == 1) { ?>
                                    <div class="alert alert-success">
                                        <button data-dismiss="alert" class="close" type="button"> ×</button>
                                        <strong>Stock</strong> has been transfered successfully!
                                    </div>
                                <?php } ?>
                                <div class="dataTables_wrapper form-inline">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <?php $this->recordsPerPage($this->counter); ?>
                                        </div>
                                        <div class="col-md-9">
                                            <div class="dataTables_filter">
                                                <label>
                                                    <a class="btn btn-primary" href="<?php echo $this->baseUrl(); ?>/stock/stock-bin-placement-vaccines?id=<?php echo $this->id; ?>">
                                                        <?php echo $this->translate("Place More"); ?>
                                                    </a>
                                                    <a onclick="window.open('<?php echo $this->baseUrl(); ?>/stock/stock-in-bin-vaccines-print?id=<?php echo $this->id; ?>&asset=<?php echo $this->title; ?>', '_blank', 'scrollbars=1,width=860,height=595');" href="javascript:void(0);" class="btn btn-success">
                                                        <?php echo $this->translate("Print"); ?>
                                                    </a>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <table class="table table-striped table-bordered table-condensed dataTable">
                                        <!-- Table heading -->
                                        <?php
                                        $array = array(
                                            "product" => "Product",
                                            "batch_no" => "Batch No",
                                            "expiry" => "Expiry Date",
                                            "qty" => "Quantity",
                                            "vvm_stage" => "VVM Stage"
                                        );
                                        $this->tableHeading($this->order, $this->sort, $array);
                                        ?>
                                        <!-- // Table heading END -->
                                        <!-- Table body -->

                                        <!-- // Table body END -->
                                        <tbody>
                                            <?php
                                            if ($this->result && count($this->result) > 0) {
                                                foreach ($this->result as $row) {
                                                    ?>
                                                    <tr class="gradeX">
                                                        <td class="left"><?php echo $row['itemName']; ?></td>
                                                        <td class="left"><?php echo $row['number']; ?></td>
                                                        <td class="right"><?php echo $row['expiry']; ?></td>
                                                        <td class="right"><?php echo number_format($row['qty']); ?></td>
                                                        <td class="right"><?php echo $row['vvmStage']; ?></td>
                                                        <td>
                                                            <a editid="<?php echo $row['pkId']; ?>" class="btn transfer-stock-vaccines btn-link btn-success btn-sm" data-toggle="modal" href="#modal-transfer-stock-vaccines">
                                                                <?php echo $this->translate("Transfer") ?>
                                                            </a>
                                                            <!--<a data-toggle="notyfy" id="<?php //echo $row->getPlacementLocation()->getPkId();   ?>" data-type="confirm" data-layout="top" class="cursor-hand btn btn-danger btn-sm">
                                                            <?php //echo $this->translate("Delete") ?>
                                                            </a> -->
                                                            <a class="btn btn-info btn-sm" id="<?php echo $row['batch_id']; ?>-batchdetail" data-id="<?php echo $row['batch_id']; ?>" data-toggle="modal" href="#information"><i class="fa fa-search"></i></a>

                                                        </td>
                                                <input type="hidden" id="totqty" name="totqty[<?php echo $row['pkId']; ?>]" value="<?php echo $row['qty']; ?>"/>
                                                <input type="hidden" id="area" name="area" value="<?php echo $this->area; ?>"/>
                                                <input type="hidden" id="level" name="level" value="<?php echo $this->level; ?>"/>
                                                </tr>
                                                <?php
                                            }
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                    <?php echo $this->paginationControl($this->result, 'Sliding', 'paginator.phtml', array('params' => $this->pagination_params)); ?>
                                </div>
                                <input type="hidden" id="bin_id" value="<?php echo $this->bin_id; ?>"/>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <form method="post" action="<?php echo $this->baseUrl(); ?>/stock/transfer-stock-vaccines" id="transfer-stock-vaccines">
                                    <div class="modal fade" id="modal-transfer-stock-vaccines" tabindex="-1" role="basic" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                    <h3>Transfer Stock</h3>
                                                </div>
                                                <div class="modal-body" id="modal-body-contents">
                                                    <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>
                                                </div>
                                                <div class="modal-footer hide" id="transfer-button">
                                                    <input class="btn btn-primary" type="submit" value="<?php echo $this->translate("Transfer"); ?>">

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <input type="hidden" value="<?php echo $this->title; ?>" name="asset_name" id="asset_name">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?php
                require_once 'FusionCharts/Code/PHP/Includes/FusionCharts.php';
                FC_SetRenderer('javascript');
                echo renderChart($this->baseUrl() . "/FusionCharts/Charts/Pie3D.swf", "", $this->xmlstore, 'DataEntryStatus', '100%', 250, false, false);
                ?>
            </div>
        </div> 
    </div>
</div>
<!-- // Content END -->
<!-- /.modal -->
<div id="information" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Batch Placements Detail</h4>
            </div>
            <div class="modal-body" id="batchdetailbody">

            </div>
        </div>
    </div>