<?php

/**
 * Model_Users
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Logistics Management Information System for Vaccines
 * @subpackage Inventory Management
 * @author     Ajmal Hussain <ajmaleyetii@gmail.com>
 * @version    2
 */
class Model_Users extends Model_Base {

    protected $_table;

    public function __construct() {
        parent::__construct();
        $this->_table = $this->_em->getRepository('Users');
    }

    public function getUsers($order = null, $sort = null) {
        if (!empty($this->form_values)) {
            return $this->_table->findBy($this->form_values);
        } else {
            $qry = $this->_em->createQueryBuilder()
                    ->select("u")
                    ->from("Users", "u")
                    ->join("u.role", "r")
                    ->join("u.createdBy", "cb")
                    ->where("r.category = " . Model_Roles::COLDCHAIN);

            if ($order == 'login_id') {
                $qry->orderBy("u.loginId", $sort);
            }
            if ($order == 'role') {
                $qry->orderBy("r.roleName", $sort);
            }
            if ($order == 'created_by') {
                $qry->orderBy("cb.userName", $sort);
            }
            if ($order == 'logged_at') {
                $qry->orderBy("u.loggedAt", $sort);
            }

            return $qry->getQuery()->getResult();
        }
    }

    public function getAllUsers($order = null, $sort = null) {
        $form_values = $this->form_values;


        if (!empty($form_values['page']) && $form_values['page'] == 'routine') {
            $where[] = "s.pkId =  '9' and r.pkId='8'   ";
        }
        if (!empty($form_values['page']) && $form_values['page'] == 'campaigns') {
            $where[] = "s.pkId =  '10' and r.pkId IN (14,15,16) ";
        }
        if (!empty($form_values['page']) && $form_values['page'] == 'im') {
            $where[] = "s.pkId = '1' and r.pkId='8' ";
        }
        if (!empty($form_values['page']) && $form_values['page'] == 'policy') {
            $where[] = "s.pkId = '1' and r.pkId='17'";
        }
        if (!empty($form_values['search_policy_users'])) {
            $where[] = "u.loginId =  '" . $form_values['search_policy_users'] . "' ";
        }
        if (!empty($form_values['office_type']) && $form_values['office_type'] == 1) {
            $where[] = "so.pkId =  '" . $form_values['office_type'] . "' ";
        }
        if (!empty($form_values['combo1'])) {
            $where[] = "p.pkId = '" . $form_values['combo1'] . "' and  so.pkId =  '" . $form_values['office_type'] . "' ";
        }
//        if (!empty($form_values['combo1'])) {
//            $where[] = "p.pkId = '" . $form_values['combo1'] . "' and  so.pkId =  '" . $form_values['office_type'] . "' ";
//        }
        if (!empty($form_values['combo2'])) {
            $where[] = "d.pkId = '" . $form_values['combo2'] . "' and  so.pkId =  '" . $form_values['office_type'] . "' ";
        }
        if (!empty($form_values['combo3'])) {
            $where[] = "l.pkId = '" . $form_values['combo3'] . "' and  so.pkId =  '" . $form_values['office_type'] . "' ";
        }
        if (!empty($form_values['combo4'])) {
            $where[] = "l.pkId = '" . $form_values['combo4'] . "' and  so.pkId =  '" . $form_values['office_type'] . "' ";
        }
        if (is_array($where)) {
            $where_s = implode(" AND ", $where);
        }

        $qry = $this->_em->createQueryBuilder()
                ->select("u.pkId,u.loginId,p.locationName as ProvinceName,d.locationName as districtName,l.locationName as Parent,"
                        . "s.stakeholderName")
                ->from("WarehouseUsers", "wu")
                ->join("wu.user", "u")
                ->join("u.role", "r")
                ->join("wu.warehouse", "w")
                ->join("w.location", "l")
                ->join("l.province", "p")
                ->join("l.district", "d")
                ->join("w.stakeholderOffice", "so")
                ->join("u.stakeholder", "s")
                ->where($where_s);
        echo $qry->getQuery()->getSql();

        return $qry->getQuery()->getResult();
    }

    public function getAllImUsers($order = null, $sort = null) {
        $form_values = $this->form_values;
        //   $where = "r.pkId='8' ";

        $where[] = "s.pkId = '1'  ";

        if (!empty($form_values['office_type'])) {
            $where[] = "so.pkId =  '" . $form_values['office_type'] . "' ";
        }
        if (!empty($form_values['combo1'])) {
            $where[] = "p.pkId = '" . $form_values['combo1'] . "' ";
        }

        if (!empty($form_values['combo2'])) {
            $where[] = "d.pkId = '" . $form_values['combo2'] . "'  ";
        }
        if (!empty($form_values['combo3'])) {
            $where[] = "l.pkId = '" . $form_values['combo3'] . "'  ";
        }
        if (!empty($form_values['combo4'])) {
            $where[] = "l.pkId = '" . $form_values['combo4'] . "'  ";
        }
        if (is_array($where)) {
            $where_s = implode(" AND ", $where);
        }

        $qry = $this->_em->createQueryBuilder()
                ->select("u.pkId,u.loginId,r.pkId as role,p.locationName as ProvinceName,d.locationName as districtName,l.locationName as Parent,"
                        . "s.stakeholderName")
                ->from("WarehouseUsers", "wu")
                ->join("wu.user", "u")
                ->join("u.role", "r")
                ->join("wu.warehouse", "w")
                ->join("w.location", "l")
                ->join("l.province", "p")
                ->join("l.district", "d")
                ->join("w.stakeholderOffice", "so")
                ->join("u.stakeholder", "s")
                ->where($where_s);
//echo $qry->getQuery()->getSql();

        return $qry->getQuery()->getResult();
    }

    public function getUserIdByWarehouseId($wh_id) {
        $user = Zend_Registry::get('doctrine')->getRepository('WarehouseUsers')->findOneBy(array("warehouse" => $wh_id, "isDefault" => 1));
        if (count($user) > 0) {
            return $user->getUser()->getPkId();
        } else {
            return false;
        }
    }
    
    public function updateUserToken($hash, $wh_id) {
        $user_id = $this->getUserIdByWarehouseId($wh_id);
        $user = Zend_Registry::get('doctrine')->getRepository('Users')->find($user_id);
        $user->setAuth($hash);
        
        $this->_em->persist($user);
        $this->_em->flush();
        
        return array(array("message" => "Hash has been updated successfully", "login_id" => $user->getLoginId(), "user_id" => $user->getPkId()));
    }
    
    public function getRIUsers() {
        $form_values = $this->form_values;
        $qry = $this->_em->createQueryBuilder()
                ->select("wu")
                ->from("WarehouseUsers", "wu")
                ->join("wu.user", "u")
                ->join("u.role", "r")
                ->join("wu.warehouse", "w")
                ->join("w.stakeholderOffice", "so")
                ->where("so.geoLevel = 6");
        if (!empty($form_values['loc_id'])) {
            $qry->andWhere("w.location = " . $form_values['loc_id']);
        }
        $qry->andWhere("r.pkId = 8");
        return $qry->getQuery()->getResult();
    }

    public function getAllCampaignUsers($order = null, $sort = null) {
        $form_values = $this->form_values;
        if (!empty($form_values['office_type']) && $form_values['office_type'] == 1 || $form_values['office_type'] == 2) {

            if (!empty($form_values['page']) && $form_values['page'] == 'campaigns') {
                $where[] = "s.pkId =  '10' AND r.pkId IN (14,15) ";
            }
            if (!empty($form_values['office_type']) && $form_values['office_type'] == 1) {
                $where[] = "l.pkId = '10'  ";
            }
            if (!empty($form_values['combo1'])) {
                $where[] = "l.pkId = '" . $form_values['combo1'] . "'  ";
            }

            if (is_array($where)) {
                $where_s = implode(" AND ", $where);
            }

            $qry = $this->_em->createQueryBuilder()
                    ->select("DISTINCT u.pkId,u.loginId,l.locationName as ProvinceName,l.locationName as districtName,l.locationName as Parent,"
                            . "s.stakeholderName")
                    ->from("Users", "u")
                    ->join("u.role", "r")
                    ->join("u.location", "l")
                    ->join("u.stakeholder", "s")
                    ->where($where_s);
            return $qry->getQuery()->getResult();
        }

        if (!empty($form_values['office_type']) && $form_values['office_type'] == 4) {

            if (!empty($form_values['page']) && $form_values['page'] == 'campaigns') {
                $where[] = "s.pkId =  '10' and r.pkId='16' ";
            }
            if (!empty($form_values['office_type']) && $form_values['office_type'] == 1) {

                $where[] = "l.pkId = '10'  ";
            }

            if (!empty($form_values['combo1'])) {
                $where[] = "p.pkId = '" . $form_values['combo1'] . "'  ";
            }

            if (!empty($form_values['combo2'])) {
                $where[] = "d.pkId = '" . $form_values['combo2'] . "' ";
            }

            if (is_array($where)) {
                $where_s = implode(" AND ", $where);
            }

            $qry = $this->_em->createQueryBuilder()
                    ->select("DISTINCT u.pkId,u.loginId,p.locationName as ProvinceName,d.locationName as districtName,l.locationName as Parent,"
                            . "s.stakeholderName")
                    ->from("WarehouseUsers", "wu")
                    ->join("wu.user", "u")
                    ->join("u.role", "r")
                    ->join("wu.warehouse", "w")
                    ->join("u.location", "l")
                    ->join("l.province", "p")
                    ->join("l.district", "d")
                    ->join("w.stakeholderOffice", "so")
                    ->join("u.stakeholder", "s")
                    ->where($where_s);
            return $qry->getQuery()->getResult();
        }
    }

    public function getCampaignUsers() {
        $form_values = $this->form_values;

        $type = '';
        if (!empty($form_values['office_type'])) {
            $type = $form_values['office_type'];
        }

        switch ($type) {
            case 1:
                $role = 14;
                $loc_id = 10;
                break;
            case 2:
                $role = 15;
                $loc_id = $form_values['combo1'];
                break;
            case 4:
                $role = 16;
                $loc_id = $form_values['combo2'];
                break;
            default:
                $role = "14,15,16";
                break;
        }

        $qry = $this->_em->createQueryBuilder()
                ->select("DISTINCT u")
                ->from("Users", "u")
                ->where("u.role IN ($role)");
        if (!empty($loc_id)) {
            $qry->andWhere("u.location = $loc_id");
        }
        return $qry->getQuery()->getResult();
    }

    public function getAllPolicyUsers($order = null, $sort = null) {
        $form_values = $this->form_values;

        $type = '';
        if (!empty($form_values['office_type'])) {
            $type = $form_values['office_type'];
        }

        switch ($type) {
            case 1:
                $role = 17;
                $loc_id = 10;
                break;
            case 2:
                $role = 19;
                $loc_id = $form_values['combo1'];
                break;
            case 4:
                $role = 20;
                $loc_id = $form_values['combo2'];
                break;
            default:
                $role = "17,19,20";
                break;
        }

        $qry = $this->_em->createQueryBuilder()
                ->select("DISTINCT u")
                ->from("Users", "u")
                ->where("u.role IN ($role)");
        if (!empty($loc_id)) {
            $qry->andWhere("u.location = $loc_id");
        }
        // echo $qry->getQuery()->getSql();
        return $qry->getQuery()->getResult();
    }

    public function getAllUsersForCluster() {
        $form_values = $this->form_values;

        $qry = $this->_em->createQueryBuilder()
                ->select("Distinct u.loginId,u.pkId")
                ->from("WarehouseUsers", "wu")
                ->join("wu.user", "u")
                ->join("wu.warehouse", "w")
                ->join("w.stakeholderOffice", "s")
                ->join("w.district", "d")
                ->where("d.pkId=" . $form_values['district_id'])
                ->AndWhere("s.pkId=6");
        echo $qry->getQuery()->getSql();
        return $qry->getQuery()->getResult();
    }

    public function checkUsers() {

        $form_values = $this->form_values;

        if ($form_values['office_type_add'] == 1) {
            $str_sql = $this->_em->createQueryBuilder()
                    ->select("u.userName")
                    ->from('Users', 'u')
                    ->where("u.userName= '" . $form_values['user_name_add'] . "' ");

            $rs = $str_sql->getQuery()->getResult();
            return $rs;
        }
        if ($form_values['office_type_add'] != 1) {
            $where = "p.pkId='" . $form_values['province'] . "'  ";
            // if (is_array($where)) {
            //     $where_s = implode(" AND ", $where);
            // }
            $str_sql = $this->_em->createQueryBuilder()
                    ->select("u.userName")
                    ->from('Users', 'u')
                    ->join('u.location', 'p')
                    ->where("u.userName= '" . $form_values['user_name_add'] . "' ")
                    ->AndWhere($where);

            $rs = $str_sql->getQuery()->getResult();
            return $rs;
        }
    }

    public function checkUsersUpdate() {

        $form_values = $this->form_values;

        if ($form_values['office_type_edit'] == 1) {
            $str_sql = $this->_em->createQueryBuilder()
                    ->select("u.userName")
                    ->from('Users', 'u')
                    ->where("u.userName= '" . $form_values['user_name_update'] . "' ");

            $rs = $str_sql->getQuery()->getResult();
            return $rs;
        }
        if ($form_values['office_type_edit'] != 1) {
            $where = "p.pkId='" . $form_values['province'] . "'  ";
            // if (is_array($where)) {
            //     $where_s = implode(" AND ", $where);
            // }
            $str_sql = $this->_em->createQueryBuilder()
                    ->select("u.userName")
                    ->from('Users', 'u')
                    ->join('u.location', 'p')
                    ->where("u.userName= '" . $form_values['user_name_update'] . "' ")
                    ->AndWhere($where);

            $rs = $str_sql->getQuery()->getResult();
            return $rs;
        }
    }

    public function checkUsersUpdatePolicy() {

        $form_values = $this->form_values;
        $str_sql = $this->_em->createQueryBuilder()
                ->select("u.userName")
                ->from('Users', 'u')
                ->where("u.userName= '" . $form_values['user_name_update'] . "' ");

        $rs = $str_sql->getQuery()->getResult();
        return $rs;
    }

    public function checkUsersPolicy() {

        $form_values = $this->form_values;
        $str_sql = $this->_em->createQueryBuilder()
                ->select("u.userName")
                ->from('Users', 'u')
                ->where("u.userName= '" . $form_values['user_name_add'] . "' ");

        $rs = $str_sql->getQuery()->getResult();
        return $rs;
    }

}
