StockReceiveFromScanner:
  type: entity
  table: stock_receive_from_scanner
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    quantity:
      type: integer
      unsigned: false
      nullable: true
    vvmStage:
      type: integer
      unsigned: false
      nullable: true
      column: vvm_stage
  oneToOne:
    placementLocation:
      targetEntity: PlacementLocations
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        placement_location_id:
          referencedColumnName: pk_id
      orphanRemoval: false
    stockDetail:
      targetEntity: StockDetail
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_detail_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
