StockBatchVvm:
  type: entity
  table: stock_batch_vvm
  fields:
    pkId:
      id: true
      type: integer
      unsigned: false
      nullable: false
      column: pk_id
      generator:
        strategy: IDENTITY
    vvmStage:
      type: integer
      unsigned: false
      nullable: true
      column: vvm_stage
    quantity:
      type: decimal
      nullable: true
  oneToOne:
    stockBatch:
      targetEntity: StockBatch
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        stock_batch_id:
          referencedColumnName: pk_id
      orphanRemoval: false
  lifecycleCallbacks: {  }
