<?php
$result = $this->result[0];
$data = $this->data;

if (!empty($result)) {
    ?>
<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <span id="name"><?php echo $result['itemName']; ?></span>
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-3">
                            <h5><b><?php echo $this->translate("Batch Status"); ?></b></h5>
                            <p><?php echo $this->translate("Running"); ?></p>
                            <p><?php echo $this->translate("Stacked"); ?></p>
                           
                            <h5><b><?php echo $this->translate("Total"); ?></b></h5>
                        </div>
                        <div class="col-md-3 center">
                            <h5><b><?php echo $this->translate("No of Batches"); ?></b></h5>
                            <p id="running"><?php echo (!empty($result['running']) ? $result['running'] : 0 ); ?></p>
                            <p id="stacked"><?php echo (!empty($result['stacked']) ? $result['stacked'] : 0 ); ?></p>
                          

                            <h5 id="total"><b><?php echo ($result['running'] + $result['stacked'] ); ?></b></h5>
                        </div>
                        <div class="col-md-3 center">
                            <h5><b><?php echo $this->translate("Qty"); ?>
                                <?php
                                if ($result['itemUnitId'] == 2) {
                                    echo $this->translate("in Doses");
                                } else if ($result['itemUnitId'] == 3) {
                                    echo $this->translate("in Pcs");
                                }
                                ?></b>
                            </h5>
                            <p><?php echo number_format($data['running_doses']); ?></p>
                            <p><?php echo number_format($data['stacked_doses']); ?></p>
<!--                            <p><?php //echo number_format($data['finished_doses']); ?></p>-->
                            <h5><b><?php echo number_format($data['total']); ?></b></h5>
                        </div>
                        <?php if ($result['itemUnitId'] == 2) { ?>
                        <div class="col-md-3 center">
                            <h5><b><?php echo $this->translate("Qty in Vials"); ?></b></h5>
                            <p><?php echo number_format($result['RunningQty']); ?></p>
                            <p><?php echo number_format($result['StackedQty']); ?></p>
<!--                            <p><?php //echo number_format($result['FinishedQty']); ?></p>-->
                            <h5><b><?php echo number_format($result['RunningQty'] + $result['StackedQty'] + $result['FinishedQty']); ?></b></h5>
                        </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php } ?>