<!-- Content -->
<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #e5e5e5;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #e5e5e5;
    }
    table#mytable tr th {
        border: 1px solid #e5e5e5;
    }
</style>
<!-- Content -->

<style type="text/css" media="print">
    .page
    {
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print
    {    
        #printButt
        {
            display: none !important;
        }
    }
</style>

<?php if (!empty($this->data) && count($this->data) > 0) { ?>    
    <table id="mytable">

        <!-- Table heading -->
        <thead>
            <tr>
                <th rowspan="2"><?php echo $this->translate("Sr No"); ?></th>
                <th rowspan="2"><?php echo $this->translate("Product"); ?></th>
                <th rowspan="2"><?php echo $this->translate("Batch No"); ?></th>
                <th rowspan="2"><?php echo $this->translate("Expiry Date"); ?></th>
                <th colspan="3" width="18%" align="center"><?php echo $this->translate("Quantity"); ?></th>
                <th rowspan="2"><?php echo $this->translate("Status"); ?></th>
            </tr>
            <tr style="background-color: #F8F8F8;">
                <th ><?php echo $this->translate("Vials/Pcs"); ?></th>
                <th ><?php echo $this->translate("Doses Per Vial"); ?></th>
                <th ><?php echo $this->translate("Total Doses"); ?></th>
            </tr>
        </thead>
        <!-- // Table heading END -->

        <!-- Table body -->
        <tbody>
            <?php
            $i = 1;
            foreach ($this->data as $row) {
                ?>

                <!-- Table row -->
                <tr class="gradeX">
                    <td align="right"><?php echo $i; ?></td>
                    <td align="left"><?php echo $row['itemName']; ?></td>
                    <td align="right"> <?php echo $row['number']; ?></td>

                    <td align="center"><?php echo date("m/d/y", strtotime($row['expiryDate'])); ?></td>
                    <td align="right"><?php echo number_format($row['BatchQty']) . ' ' . $row['itemUnitName']; ?></td>
                    <td align="right"><?php echo number_format($row['BatchQty']); ?></td>
                    <td align="right"><?php echo number_format($row['BatchQty'] * $row['description']); ?></td>
                    <td align="right" id="batch<?php echo $row['pkId']; ?>-status"> &nbsp; <?php echo $row['status']; ?></td>
                </tr>

                <?php
                $i++;
            }
            ?>
            <!-- // Table row END -->
        </tbody>
        <!-- // Table body END -->

    </table>
    <!-- // Table END -->
<?php } ?>
<?php if (!empty($this->summary) && count($this->summary) > 0) { ?>
    <table style="width:100%;">
        <tr>
            <td class="left"><b style="font-size: 16px;">Product wise stock summary</b></td>
        </tr>        
    </table>
    <table id="mytable">
        <thead>
            <tr>
                <th rowspan="2">S. No.</th>
                <th rowspan="2">Product</th>
                <th colspan="3">Quantity</th>
            </tr>
            <tr style="background-color: #F8F8F8;">
                <th width="10%">Vials/Pcs</th>
                <th width="15%">Doses Per Vial</th>
                <th width="15%">Total Doses</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;
            foreach ($this->summary as $summary) {
                ?>
                <!-- Table row -->
                <tr>
                    <td align="center"><?php echo $i; ?></td>
                    <td align="left"><?php echo $summary['itemName']; ?></td>
                    <td align="right"><?php echo number_format($summary['Vials']); ?></td>
                    <td align="right"><?php echo $summary['description']; ?></td>

                    <td align="right"><?php echo number_format($summary['Doses']); ?></td>

                </tr>
                <?php
                $i++;
            }
            ?>
            <!-- // Table row END -->
        </tbody>
    </table>
    <br>
    <b>Print Date:</b> <?php echo date("d/m/Y h:i:s A"); ?>
<?php } ?>            
<div>
    <div class="widget-body right">
        <button name="print" id="print" value="1" type="button" class="btn btn-primary"><?php echo $this->translate("Print"); ?></button> 
    </div>
</div>        

<!-- // Content END -->