<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <form method="POST" name="batch_search" id="batch_search" action="" >
                    <!-- Row -->
                    <div class="row">
                        <div class="col-md-6">
                            <div class="portlet box green">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-arrow-down"></i><?php echo $this->translate("Search"); ?>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="control-group">
                                                <label class="control-label" for="item_pack_size_id">
                                                    <?php echo $this->translate("Product"); ?>
                                                </label>
                                                <div class="controls">
                                                    <?php echo $this->form->item_pack_size_id; ?>
                                                </div>
                                            </div>                                                        
                                        </div>
                                        <div class="col-md-6">
                                            <div class="control-group" style="<?php echo (!empty($product)) ? 'display:none' : 'display:block'; ?>" id="printSummary">
                                                <label class="control-label">
                                                    &nbsp;
                                                </label>
                                                <div class="controls">
                                                    <button type="button" class="btn btn-primary" onclick="window.open('<?php echo $this->baseUrl(); ?>/stock-batch/batch-summary', '_blank', 'scrollbars=1,width=860,height=595');">
                                                        <?php echo $this->translate("Summary"); ?>
                                                    </button>
                                                    <button type="button" class="btn btn-primary" onclick="window.open('<?php echo $this->baseUrl(); ?>/stock-batch/stakeholder-summary', '_blank', 'scrollbars=1,width=860,height=595');">
                                                        <?php echo $this->translate("Manufacturers"); ?>
                                                    </button>
                                                </div>
                                            </div>                                                        
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <!-- Group -->
                                            <div class="control-group">
                                                <label class="control-label" for="firstname">
                                                    <?php echo $this->translate("Batch No"); ?>
                                                </label>
                                                <div class="controls">
                                                    <?php echo $this->form->number; ?>
                                                </div>
                                            </div>
                                            <!-- // Group END -->
                                        </div>
                                        <div class="col-md-6">
                                            <!-- Group -->
                                            <div class="control-group">
                                                <label class="control-label" for="firstname">
                                                    <?php echo $this->translate("Ref No"); ?>
                                                </label>
                                                <div class="controls">
                                                    <?php echo $this->form->transaction_refernece; ?>
                                                </div>
                                            </div>
                                            <!-- // Group END -->
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="control-group">
                                                <label class="control-label" for="status">
                                                    &nbsp;
                                                </label>
                                                <div class="controls">
                                                    <?php echo $this->form->status; ?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 right">
                                            <div class="control-group">
                                                <label class="control-label" for="status">
                                                    &nbsp;
                                                </label>
                                                <div class="controls">
                                                    <button class="btn btn-success" id="search" name="search" type="submit" >
                                                        <?php echo $this->translate("Search"); ?>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6" id="vaccine-detail">
                            <div id="batch_detail_ajax">
                                <p class="center"> Please select any product. Detail will display here. </p>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row margin-top-10">
            <div class="col-md-12">
                <?php
                echo App_Controller_Functions::getPageNarrative(Zend_Registry::get('resource'));
                ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="portlet box green">
                    <div class="portlet-title">
                        <div class="caption">
                            <?php echo $this->translate("Batch List"); ?>
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="batchManagement table table-striped table-bordered table-hover table-full-width" id="batch_management">
                                    <!-- Table heading -->
                                    <thead>
                                        <tr>
                                            <th><?php echo $this->translate("Sr No"); ?></th>
                                            <th><?php echo $this->translate("Product"); ?></th>
                                            <th><?php echo $this->translate("Batch No"); ?></th>
                                            <th><?php echo $this->translate("Vvm Stage"); ?></th>
                                            <th><?php echo $this->translate("Expiry Date"); ?></th>
                                            <th><?php echo $this->translate("Quantity") . " (" . (!empty($this->data[0]['itemUnitName']) ? $this->data[0]['itemUnitName'] : '' ) . ")"; ?></th>
                                            <th><?php echo $this->translate("Doses"); ?></th>
                                            <th><?php echo $this->translate("Status"); ?></th>
                                            <th><?php echo $this->translate("Action"); ?></th>
                                        </tr>
                                    </thead>
                                    <!-- // Table heading END -->
                                    <tfoot>
                                        <tr>
                                            <th colspan="5" class="right">Page Total:</th>
                                            <th class="right"></th>
                                            <th class="right"></th>
                                            <th colspan="2"></th>
                                        </tr>
                                    </tfoot>
                                    <!-- Table body -->
                                    <tbody>
                                        <?php
                                        if (!empty($this->data) && count($this->data) > 0) {
                                            $i = 1;
                                            foreach ($this->data as $row) {


                                                $placement_history = $row['pkId'] . '|' . $row['itemName'] . '|' . $row['number'] . '|' . $row['expiryDate'];

                                                if ($row['BatchQty'] < 0) {
                                                    $row['BatchQty'] = 0;
                                                }
                                                ?>
                                                <!-- Table row -->
                                                <tr class="gradeX">
                                                    <td><?php echo $i; ?></td>
                                                    <td><?php echo $row['itemName']; ?></td>
                                                    <td><?php echo $row['number']; ?></td>
                                                    <td><?php $this->batchVvmStage($row['pkId']); ?></td>
                                                    <td <?php if ($this->isExpiryEdit($row['pkId'])) { ?>class="editableSingle expiry id<?php echo $row['pkId']; ?>" <?php } ?>><?php echo date("d/m/Y", strtotime($row['expiryDate'])); ?></td>
                                                    <td class="right col-md-1"><?php echo number_format($row['BatchQty']); ?></td>
                                                    <td class="right col-md-1"><?php echo number_format($row['BatchQty'] * $row['description']); ?></td>
                                                    <td id="batch<?php echo $row['pkId']; ?>-status"> &nbsp; <?php echo $row['status']; ?></td>
                                                    <td class="col-md-2">
                                                        <input type="hidden" name="status" id="batch<?php echo $row['pkId']; ?>_status" value="<?php echo $row['status']; ?>" />
                                                        <input type="hidden" name="batch_id" id="batch<?php echo $row['pkId']; ?>_id" value="<?php echo $row['pkId']; ?>" />
                                                                                                            
                                                            <?php
                                                            if ($row['status'] == 'Finished') {
                                                                echo '';
                                                            } else {
                                                                ?>
                                                                <button class="btn <?php echo ($row['status'] == 'Stacked') ? "btn-success" : "btn-danger"; ?> input-sm" id="batch<?php echo $row['pkId']; ?>-makeit">
                                                                    <?php echo $this->translate("Make it"); ?>
                                                                    <span id="batch<?php echo $row['pkId']; ?>-button">
                                                                        <?php echo ($row['status'] == 'Stacked') ? "Running" : "Stacked"; ?>
                                                                    </span>
                                                                </button>
                                                                <?php
                                                            }
                                                            ?>
                                                         
                                                                <div class="label label-sm label-info">
                                                                    <a pkid="<?php echo $placement_history; ?>" class="placement-history white"  data-toggle="modal" title="Placement Info" href="#modal-placement-history">
                                                                        <i class="fa fa-search">  </i>   </a>           
                                                                </div></td>
                                                        </tr>
                                                        <?php
                                                        $i++;
                                                    }
                                                }
                                                ?>
                                                <!-- // Table row END -->
                                            </tbody>
                                            <!-- // Table body END -->

                                        </table>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group pull-right">
                                            <button id="print_vaccine_placement" type="button" class="btn btn-primary input-sm" >
                                                <?php echo $this->translate("Print"); ?>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="modal-detail-batch" tabindex="-1" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3>Placement Location</h3>
                    </div>

                    <div class="modal-body" id="modal-body-contents-detail">
                        <div style="text-align: center; "><img src="<?php echo $this->baseUrl(); ?>/images/loader.gif"/></div>                  
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-placement-history" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3>Batch Placements Detail</h3>
            </div>
            <div class="modal-body" id="modal-body-contents"></div>
        </div>
    </div>
</div>
