<!-- Content -->
<style>
    #content_print {
        margin-left: 50px;
        width: 624px;
    }
    table#mytable {
        border: 1px solid #e5e5e5;
        font-size: 9pt;
        width: 100%;
    }
    table#mytable tr td {
        border: 1px solid #e5e5e5;
    }
    table#mytable tr th {
        border: 1px solid #e5e5e5;
    }
</style>
<!-- Content -->

<style type="text/css" media="print">
    .page
    {
        -webkit-transform: rotate(-90deg); -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    @media print
    {    
        #printButt
        {
            display: none !important;
        }
    }
</style>

<?php if (!empty($this->summary) && count($this->summary) > 0) { ?>
    <table id="mytable">
        <thead>
            <tr>
                <th rowspan="2">S. No.</th>
                <th rowspan="2">Product</th>
                <th rowspan="2">Manufacturer</th>                
                <th colspan="3">Quantity</th>
            </tr>
            <tr style="background-color: #F8F8F8;">
                <th width="10%">Vials/Pcs</th>
                <th width="15%">Total Doses</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;
            foreach ($this->summary as $summary) {
                ?>
                <!-- Table row -->
                <tr>
                    <td align="center"><?php echo $i; ?></td>
                    <td align="left"><?php echo $summary['itemName']; ?></td>
                    <td align="left"><?php echo $summary['stakeholderName']; ?></td>                    
                    <td align="right"><?php echo number_format($summary['Vials']); ?></td>
                    <td align="right"><?php echo number_format($summary['Doses']); ?></td>
                </tr>
                <?php
                $i++;
            }
            ?>
            <!-- // Table row END -->
        </tbody>
    </table>
<?php } ?>            
<div>
    <div class="widget-body right">
        <button name="print" id="print" value="1" type="button" class="btn btn-primary"><?php echo $this->translate("Print"); ?></button> 
    </div>
</div>        

<!-- // Content END -->